services:
  # Products domain microservices
  products-db:
    build:
      context: ../BackEnd/DataBases/products
      dockerfile: Dockerfile
    container_name: products-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - my_network

  create-product:
    build:
      context: ../BackEnd/Domains/Products/CreateProduct
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://user:password@products-db:27017
    depends_on:
      - products-db
    networks:
      - my_network

  delete-product:
    build:
      context: ../BackEnd/Domains/Products/DeleteProduct
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://user:password@products-db:27017
    depends_on:
      - products-db
    networks:
      - my_network

  edit-product:
    build:
      context: ../BackEnd/Domains/Products/EditProduct
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://user:password@products-db:27017
    depends_on:
      - products-db
    networks:
      - my_network

  get-all-products:
    build:
      context: ../BackEnd/Domains/Products/GetAllProducts
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://user:password@products-db:27017
    depends_on:
      - products-db
    networks:
      - my_network

  get-product-by-id:
    build:
      context: ../BackEnd/Domains/Products/GetProductById
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://user:password@products-db:27017
    depends_on:
      - products-db
    networks:
      - my_network

  # Cart domain microservices
  get-cart-by-id:
    build:
      context: ../BackEnd/Domains/Cart/GetCartById
      dockerfile: Dockerfile
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=localDevPassword
    depends_on:
      - redis
    networks:
      - my_network

  set-cart:
    build:
      context: ../BackEnd/Domains/Cart/SetCart
      dockerfile: Dockerfile
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=localDevPassword
    depends_on:
      - redis
    networks:
      - my_network

  delete-cart:
    build:
      context: ../BackEnd/Domains/Cart/DeleteCart
      dockerfile: Dockerfile
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=localDevPassword
    depends_on:
      - redis
    networks:
      - my_network

  redis:
    build:
      context: ../BackEnd/DataBases/cart
      dockerfile: Dockerfile
    container_name: redis
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ../Dev/redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - my_network
  # User Domain
  get-user-by-id:
    build:
      context: ../BackEnd/Domains/Users/GetUserById
      dockerfile: Dockerfile
    networks:
      - my_network

  # Auth Domain
  login:
    build:
      context: ../BackEnd/Domains/Auth/Login
      dockerfile: Dockerfile
    networks:
      - my_network
    environment:
      - SECRET_KEY=my_secret_key

  logout:
    build:
      context: ../BackEnd/Domains/Auth/Logout
      dockerfile: Dockerfile
    networks:
      - my_network
    environment:
      - SECRET_KEY=my_secret_key

  role-auth:
    build:
      context: ../BackEnd/Domains/Auth/role-auth
      dockerfile: Dockerfile
    networks:
      - my_network
    environment:
      - SECRET_KEY=my_secret_key
    ports:
    - "8081:80"

  # Local API Gateway
  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    volumes:
      - ../local/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    depends_on:
      - create-product
      - delete-product
      - edit-product
      - get-all-products
      - get-product-by-id
      - get-cart-by-id
      - set-cart
      - delete-cart
      - redis
      - get-user-by-id
      - login
      - logout
      - role-auth
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
